name: ci-ts

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    working-directory: starters/playwright-ts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx tsc --noEmit
      - run: npx playwright test --list
